#!/bin/bash
# create-package
# usage: ./create-package directory-root architecture

if [ $# -lt 2 ]
then
echo usage: $0 directory-root architecture
exit 1
fi

# directories
ROOT_DIR=$1
PACKAGE_INFO_DIR=$1/DEBIAN
BIN_DIR=$1/usr/bin
MAN_DIR=$1/usr/share/man/man1

# files
CONTROL=$PACKAGE_INFO_DIR/control
BINARY=$BIN_DIR/compile
MAN_PAGE=$MAN_DIR/compile.1

# create needed directories
if [ ! -d $ROOT_DIR ]
then
mkdir $ROOT_DIR
fi
if [ ! -d $PACKAGE_INFO_DIR ]
then
mkdir $PACKAGE_INFO_DIR
fi
if [ ! -d $BIN_DIR ]
then
mkdir -p $BIN_DIR
fi
if [ ! -d $MAN_DIR ]
then
mkdir -p $MAN_DIR
fi

# create needed files
echo "Package: compile" > $CONTROL
echo "Version: 2.11" >> $CONTROL
echo "Description: invokes compiler programs with customized command-lines" >> $CONTROL
echo "Maintainer: Roger Gee <rpg11a@acu.edu>" >> $CONTROL
echo Architecture: $2 >> $CONTROL
echo "Depends: libc6" >> $CONTROL
cp compile $BINARY
cp compile.1 $MAN_PAGE
if [ -f $MAN_PAGE.gz ]
then
rm $MAN_PAGE.gz
fi
gzip $MAN_PAGE

# create .deb package
dpkg-deb --build $ROOT_DIR .
